Build started...
Build succeeded.
[21:01:53 WRN] Navigations 'User.Role' and 'Role.DeletedUser' were separated into two relationships since the [ForeignKey] attribute was specified on navigations on both sides.
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Permissions" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(20) NOT NULL,
    "Description" character varying(500) NOT NULL,
    CONSTRAINT "PK_Permissions" PRIMARY KEY ("ID")
);

CREATE TABLE "Statuses" (
    "ID" character varying(1) NOT NULL,
    "Description" character varying(50) NOT NULL,
    "Color" character varying(6) NOT NULL,
    CONSTRAINT "PK_Statuses" PRIMARY KEY ("ID")
);

CREATE TABLE "UserTypes" (
    "ID" character varying(3) NOT NULL,
    "Description" character varying(50) NOT NULL,
    CONSTRAINT "PK_UserTypes" PRIMARY KEY ("ID")
);

CREATE TABLE "RolePermissions" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleID" integer NOT NULL,
    "PermissionID" integer NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_RolePermissions_Permissions_PermissionID" FOREIGN KEY ("PermissionID") REFERENCES "Permissions" ("ID") ON DELETE CASCADE
);

CREATE TABLE "Roles" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" character varying(50) NOT NULL,
    "StatusID" character varying(1) NOT NULL,
    "RoAdmin" boolean NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    "EditUserID" integer,
    "EditDate" timestamp with time zone,
    "DeletedUserID" integer,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Roles_Statuses_StatusID" FOREIGN KEY ("StatusID") REFERENCES "Statuses" ("ID") ON DELETE CASCADE
);

CREATE TABLE "Users" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" character varying(50) NOT NULL,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "Password" text NOT NULL,
    "RoleID" integer NOT NULL,
    "UserTypeID" character varying(3) NOT NULL,
    "StatusID" character varying(1) NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    "EditUserID" integer,
    "EditDate" timestamp with time zone,
    "DeletedUserID" integer,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Users_Roles_RoleID" FOREIGN KEY ("RoleID") REFERENCES "Roles" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Users_Statuses_StatusID" FOREIGN KEY ("StatusID") REFERENCES "Statuses" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Users_UserTypes_UserTypeID" FOREIGN KEY ("UserTypeID") REFERENCES "UserTypes" ("ID") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Permissions_Code" ON "Permissions" ("Code");

CREATE UNIQUE INDEX "IX_Permissions_Description" ON "Permissions" ("Description");

CREATE INDEX "IX_RolePermissions_CreatedUserID" ON "RolePermissions" ("CreatedUserID");

CREATE INDEX "IX_RolePermissions_PermissionID" ON "RolePermissions" ("PermissionID");

CREATE INDEX "IX_RolePermissions_RoleID" ON "RolePermissions" ("RoleID");

CREATE INDEX "IX_Roles_CreatedUserID" ON "Roles" ("CreatedUserID");

CREATE INDEX "IX_Roles_DeletedUserID" ON "Roles" ("DeletedUserID");

CREATE UNIQUE INDEX "IX_Roles_Description" ON "Roles" ("Description");

CREATE INDEX "IX_Roles_EditUserID" ON "Roles" ("EditUserID");

CREATE INDEX "IX_Roles_StatusID" ON "Roles" ("StatusID");

CREATE INDEX "IX_Users_RoleID" ON "Users" ("RoleID");

CREATE INDEX "IX_Users_StatusID" ON "Users" ("StatusID");

CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");

CREATE INDEX "IX_Users_UserTypeID" ON "Users" ("UserTypeID");

ALTER TABLE "RolePermissions" ADD CONSTRAINT "FK_RolePermissions_Roles_RoleID" FOREIGN KEY ("RoleID") REFERENCES "Roles" ("ID") ON DELETE CASCADE;

ALTER TABLE "RolePermissions" ADD CONSTRAINT "FK_RolePermissions_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE;

ALTER TABLE "Roles" ADD CONSTRAINT "FK_Roles_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE RESTRICT;

ALTER TABLE "Roles" ADD CONSTRAINT "FK_Roles_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID") ON DELETE RESTRICT;

ALTER TABLE "Roles" ADD CONSTRAINT "FK_Roles_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251011114124_InitialCreate', '8.0.20');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251011142829_SyncExistingDb', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "Roles" ALTER COLUMN "CreatedUserID" DROP NOT NULL;

ALTER TABLE "Roles" ALTER COLUMN "CreationDate" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251011143257_AlterRolesNullableFields', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "Users" ALTER COLUMN "CreatedUserID" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251011144040_AlterUsersNullableFields', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "Roles" RENAME COLUMN "Admin" TO "IsAdmin";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251013063319_AlterRoleIsAdmin', '8.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" character varying(50) NOT NULL,
    "BannerImage" character varying(50),
    "Image" character varying(50),
    "AD_Image1" character varying(50),
    "AD_Image2" character varying(50),
    "AD_Image3" character varying(50),
    "AD_Details" text,
    "MobileImage" character varying(50),
    "Rank" integer NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    "EditUserID" integer,
    "EditDate" timestamp with time zone,
    "DeletedUserID" integer,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Categories_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Categories_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID"),
    CONSTRAINT "FK_Categories_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID")
);

CREATE INDEX "IX_Categories_CreatedUserID" ON "Categories" ("CreatedUserID");

CREATE INDEX "IX_Categories_DeletedUserID" ON "Categories" ("DeletedUserID");

CREATE UNIQUE INDEX "IX_Categories_Description" ON "Categories" ("Description");

CREATE INDEX "IX_Categories_EditUserID" ON "Categories" ("EditUserID");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251016092319_AddCategoriesTable', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "Categories" RENAME COLUMN "Id" TO "ID";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251016092613_RenameIDFieldCategoriesTable', '8.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE "FilePaths" (
    "Code" character varying(20) NOT NULL,
    "Description" text NOT NULL,
    CONSTRAINT "PK_FilePaths" PRIMARY KEY ("Code")
);

CREATE UNIQUE INDEX "IX_FilePaths_Description" ON "FilePaths" ("Description");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251017201045_CreatePathTable', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "Categories" DROP COLUMN "Active";

ALTER TABLE "Categories" ADD "StatusID" character varying(1) NOT NULL DEFAULT '';

CREATE INDEX "IX_Categories_StatusID" ON "Categories" ("StatusID");

ALTER TABLE "Categories" ADD CONSTRAINT "FK_Categories_Statuses_StatusID" FOREIGN KEY ("StatusID") REFERENCES "Statuses" ("ID") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251017203042_ChangeActiveToStatusIDCategoryTable', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "Categories" RENAME COLUMN "AD_Details" TO "Details";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251019102859_RenameADDetailsToDetailsCategoriesTable', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "Categories" RENAME COLUMN "Image" TO "WebImage";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251019113813_RenameImageToWebImageCategoriesTable', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "Categories" ALTER COLUMN "WebImage" TYPE character varying(500);

ALTER TABLE "Categories" ALTER COLUMN "MobileImage" TYPE character varying(500);

ALTER TABLE "Categories" ALTER COLUMN "Description" TYPE character varying(500);

ALTER TABLE "Categories" ALTER COLUMN "BannerImage" TYPE character varying(500);

ALTER TABLE "Categories" ALTER COLUMN "AD_Image3" TYPE character varying(500);

ALTER TABLE "Categories" ALTER COLUMN "AD_Image2" TYPE character varying(500);

ALTER TABLE "Categories" ALTER COLUMN "AD_Image1" TYPE character varying(500);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251101101321_IncreaseCategoryImagesLength', '8.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE "SubCategories" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" character varying(500) NOT NULL,
    "BannerImage" character varying(500),
    "WebImage" character varying(500),
    "MobileImage" character varying(500),
    "Rank" integer NOT NULL,
    "CategoryID" integer NOT NULL,
    "StatusID" character varying(1) NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    "EditUserID" integer,
    "EditDate" timestamp with time zone,
    "DeletedUserID" integer,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_SubCategories" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_SubCategories_Categories_CategoryID" FOREIGN KEY ("CategoryID") REFERENCES "Categories" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_SubCategories_Statuses_StatusID" FOREIGN KEY ("StatusID") REFERENCES "Statuses" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_SubCategories_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_SubCategories_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID"),
    CONSTRAINT "FK_SubCategories_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID")
);

CREATE INDEX "IX_SubCategories_CategoryID" ON "SubCategories" ("CategoryID");

CREATE INDEX "IX_SubCategories_CreatedUserID" ON "SubCategories" ("CreatedUserID");

CREATE INDEX "IX_SubCategories_DeletedUserID" ON "SubCategories" ("DeletedUserID");

CREATE UNIQUE INDEX "IX_SubCategories_Description" ON "SubCategories" ("Description");

CREATE INDEX "IX_SubCategories_EditUserID" ON "SubCategories" ("EditUserID");

CREATE INDEX "IX_SubCategories_StatusID" ON "SubCategories" ("StatusID");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251101185452_CreateSubCategories', '8.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE "Countries" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ISO2" character varying(2) NOT NULL,
    "ISO3" character varying(3) NOT NULL,
    "Name" character varying(100) NOT NULL,
    "ShippingCost" numeric(12,2) NOT NULL,
    "ShippingCostFixed" boolean NOT NULL,
    "Sales" boolean NOT NULL,
    "TotalRange" double precision NOT NULL,
    "MoneyTransferFees" double precision NOT NULL,
    "IP" character varying(50) NOT NULL,
    "Native" boolean NOT NULL,
    CONSTRAINT "PK_Countries" PRIMARY KEY ("ID")
);

CREATE TABLE "Clients" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "Password" text NOT NULL,
    "PasswordMobile" char(10),
    "Email" character varying(200) NOT NULL,
    "PhoneCountryID" integer NOT NULL,
    "PhoneNumber" character varying(50) NOT NULL,
    "DeviceToken" character varying(255),
    "VerificationCode" text,
    "ResetPasswordLink" text,
    "CreatedUserID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    "EditUserID" integer,
    "EditDate" timestamp with time zone,
    "DeletedUserID" integer,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Clients" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Clients_Countries_PhoneCountryID" FOREIGN KEY ("PhoneCountryID") REFERENCES "Countries" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Clients_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Clients_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID"),
    CONSTRAINT "FK_Clients_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID")
);

CREATE INDEX "IX_Clients_CreatedUserID" ON "Clients" ("CreatedUserID");

CREATE INDEX "IX_Clients_DeletedUserID" ON "Clients" ("DeletedUserID");

CREATE INDEX "IX_Clients_EditUserID" ON "Clients" ("EditUserID");

CREATE INDEX "IX_Clients_PhoneCountryID" ON "Clients" ("PhoneCountryID");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251108114655_CoutriesAndClientsTable', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "Countries" ADD "Code" character varying(50);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251108130853_AddCodeToCountries', '8.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE "ClientAddresses" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ClientID" integer NOT NULL,
    "Title" character varying(200),
    "Line1" character varying(50),
    "Line2" character varying(50),
    "StateProvince" character varying(50),
    "City" character varying(50),
    "PostalCode" character varying(50),
    "CountryID" integer NOT NULL,
    "Latitude" double precision NOT NULL,
    "Longitude" double precision NOT NULL,
    CONSTRAINT "PK_ClientAddresses" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_ClientAddresses_Clients_ClientID" FOREIGN KEY ("ClientID") REFERENCES "Clients" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_ClientAddresses_Countries_CountryID" FOREIGN KEY ("CountryID") REFERENCES "Countries" ("ID") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Countries_Name" ON "Countries" ("Name");

CREATE INDEX "IX_ClientAddresses_ClientID" ON "ClientAddresses" ("ClientID");

CREATE INDEX "IX_ClientAddresses_CountryID" ON "ClientAddresses" ("CountryID");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251108135400_CreateClientAddressesTable', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "ClientAddresses" ADD "CreatedUserID" integer NOT NULL DEFAULT 0;

ALTER TABLE "ClientAddresses" ADD "DeletedUserID" integer NOT NULL DEFAULT 0;

ALTER TABLE "ClientAddresses" ADD "EditUserID" integer NOT NULL DEFAULT 0;

ALTER TABLE "ClientAddresses" ADD "StatusID" character varying(1) NOT NULL DEFAULT '';

CREATE INDEX "IX_ClientAddresses_CreatedUserID" ON "ClientAddresses" ("CreatedUserID");

CREATE INDEX "IX_ClientAddresses_DeletedUserID" ON "ClientAddresses" ("DeletedUserID");

CREATE INDEX "IX_ClientAddresses_EditUserID" ON "ClientAddresses" ("EditUserID");

CREATE INDEX "IX_ClientAddresses_StatusID" ON "ClientAddresses" ("StatusID");

ALTER TABLE "ClientAddresses" ADD CONSTRAINT "FK_ClientAddresses_Statuses_StatusID" FOREIGN KEY ("StatusID") REFERENCES "Statuses" ("ID") ON DELETE CASCADE;

ALTER TABLE "ClientAddresses" ADD CONSTRAINT "FK_ClientAddresses_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE;

ALTER TABLE "ClientAddresses" ADD CONSTRAINT "FK_ClientAddresses_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE;

ALTER TABLE "ClientAddresses" ADD CONSTRAINT "FK_ClientAddresses_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251108140306_StatusToClientAddresses', '8.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE "Brands" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "Summary" text,
    "ShowHome" boolean NOT NULL,
    "Rank" integer NOT NULL,
    "StatusID" character varying(1) NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "EditUserID" integer NOT NULL,
    "DeletedUserID" integer NOT NULL,
    CONSTRAINT "PK_Brands" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Brands_Statuses_StatusID" FOREIGN KEY ("StatusID") REFERENCES "Statuses" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Brands_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Brands_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Brands_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE
);

CREATE INDEX "IX_Brands_CreatedUserID" ON "Brands" ("CreatedUserID");

CREATE INDEX "IX_Brands_DeletedUserID" ON "Brands" ("DeletedUserID");

CREATE INDEX "IX_Brands_EditUserID" ON "Brands" ("EditUserID");

CREATE UNIQUE INDEX "IX_Brands_Name" ON "Brands" ("Name");

CREATE INDEX "IX_Brands_StatusID" ON "Brands" ("StatusID");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251108141547_CreateBrandsTable', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "Brands" DROP CONSTRAINT "FK_Brands_Users_DeletedUserID";

ALTER TABLE "Brands" DROP CONSTRAINT "FK_Brands_Users_EditUserID";

ALTER TABLE "Brands" ALTER COLUMN "EditUserID" DROP NOT NULL;

ALTER TABLE "Brands" ALTER COLUMN "DeletedUserID" DROP NOT NULL;

ALTER TABLE "Brands" ADD "CreationDate" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Brands" ADD "DeletedDate" timestamp with time zone;

ALTER TABLE "Brands" ADD "EditDate" timestamp with time zone;

CREATE TABLE "Currencies" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(3) NOT NULL,
    "Description" character varying(100) NOT NULL,
    "Symbol" character varying(5) NOT NULL,
    "Priority" character varying(4) NOT NULL,
    "StatusID" character varying(1) NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    "EditUserID" integer,
    "EditDate" timestamp with time zone,
    "DeletedUserID" integer,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Currencies" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Currencies_Statuses_StatusID" FOREIGN KEY ("StatusID") REFERENCES "Statuses" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Currencies_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Currencies_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID"),
    CONSTRAINT "FK_Currencies_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID")
);

CREATE TABLE "Units" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ShortDescription" character varying(50) NOT NULL,
    "LongDescription" character varying(50) NOT NULL,
    "StatusID" character varying(1) NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    "EditUserID" integer,
    "EditDate" timestamp with time zone,
    "DeletedUserID" integer,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Units" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Units_Statuses_StatusID" FOREIGN KEY ("StatusID") REFERENCES "Statuses" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Units_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Units_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID"),
    CONSTRAINT "FK_Units_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID")
);

CREATE TABLE "CurrenciesConversion" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "CurrencyIDFrom" integer NOT NULL,
    "CurrencyIDTo" integer NOT NULL,
    "Operator" integer NOT NULL,
    "Rate" numeric(12,2) NOT NULL,
    "EditUserID" integer,
    "EditDate" timestamp with time zone,
    CONSTRAINT "PK_CurrenciesConversion" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_CurrenciesConversion_Currencies_CurrencyIDFrom" FOREIGN KEY ("CurrencyIDFrom") REFERENCES "Currencies" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_CurrenciesConversion_Currencies_CurrencyIDTo" FOREIGN KEY ("CurrencyIDTo") REFERENCES "Currencies" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_CurrenciesConversion_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID")
);

CREATE TABLE "Products" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(100) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" text,
    "UnitID" integer NOT NULL,
    "BrandID" integer NOT NULL,
    "VAT" boolean NOT NULL,
    "Feature" boolean NOT NULL,
    "NewArrival" boolean NOT NULL,
    "NewArrivalDateExpiryDate" date,
    "Warranty" boolean NOT NULL,
    "WarrantyMonths" integer NOT NULL,
    "VideoUrl" text NOT NULL,
    "Rank" integer NOT NULL,
    "StatusID" character varying(1) NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    "EditUserID" integer,
    "EditDate" timestamp with time zone,
    "DeletedUserID" integer,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Products" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Products_Brands_BrandID" FOREIGN KEY ("BrandID") REFERENCES "Brands" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Products_Statuses_StatusID" FOREIGN KEY ("StatusID") REFERENCES "Statuses" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Products_Units_UnitID" FOREIGN KEY ("UnitID") REFERENCES "Units" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Products_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Products_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID"),
    CONSTRAINT "FK_Products_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID")
);

CREATE TABLE "ProductsSubCategories" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "SubCategoryID" integer NOT NULL,
    "ProductID" integer NOT NULL,
    "StatusID" character varying(1) NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    "EditUserID" integer,
    "EditDate" timestamp with time zone,
    "DeletedUserID" integer,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_ProductsSubCategories" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_ProductsSubCategories_Products_ProductID" FOREIGN KEY ("ProductID") REFERENCES "Products" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductsSubCategories_Statuses_StatusID" FOREIGN KEY ("StatusID") REFERENCES "Statuses" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductsSubCategories_SubCategories_SubCategoryID" FOREIGN KEY ("SubCategoryID") REFERENCES "SubCategories" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductsSubCategories_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductsSubCategories_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID"),
    CONSTRAINT "FK_ProductsSubCategories_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID")
);

CREATE UNIQUE INDEX "IX_Currencies_Code" ON "Currencies" ("Code");

CREATE INDEX "IX_Currencies_CreatedUserID" ON "Currencies" ("CreatedUserID");

CREATE INDEX "IX_Currencies_DeletedUserID" ON "Currencies" ("DeletedUserID");

CREATE UNIQUE INDEX "IX_Currencies_Description" ON "Currencies" ("Description");

CREATE INDEX "IX_Currencies_EditUserID" ON "Currencies" ("EditUserID");

CREATE INDEX "IX_Currencies_StatusID" ON "Currencies" ("StatusID");

CREATE INDEX "IX_CurrenciesConversion_CurrencyIDFrom" ON "CurrenciesConversion" ("CurrencyIDFrom");

CREATE INDEX "IX_CurrenciesConversion_CurrencyIDTo" ON "CurrenciesConversion" ("CurrencyIDTo");

CREATE INDEX "IX_CurrenciesConversion_EditUserID" ON "CurrenciesConversion" ("EditUserID");

CREATE INDEX "IX_Products_BrandID" ON "Products" ("BrandID");

CREATE UNIQUE INDEX "IX_Products_Code" ON "Products" ("Code");

CREATE INDEX "IX_Products_CreatedUserID" ON "Products" ("CreatedUserID");

CREATE INDEX "IX_Products_DeletedUserID" ON "Products" ("DeletedUserID");

CREATE INDEX "IX_Products_EditUserID" ON "Products" ("EditUserID");

CREATE UNIQUE INDEX "IX_Products_Name" ON "Products" ("Name");

CREATE INDEX "IX_Products_StatusID" ON "Products" ("StatusID");

CREATE INDEX "IX_Products_UnitID" ON "Products" ("UnitID");

CREATE INDEX "IX_ProductsSubCategories_CreatedUserID" ON "ProductsSubCategories" ("CreatedUserID");

CREATE INDEX "IX_ProductsSubCategories_DeletedUserID" ON "ProductsSubCategories" ("DeletedUserID");

CREATE INDEX "IX_ProductsSubCategories_EditUserID" ON "ProductsSubCategories" ("EditUserID");

CREATE INDEX "IX_ProductsSubCategories_ProductID" ON "ProductsSubCategories" ("ProductID");

CREATE INDEX "IX_ProductsSubCategories_StatusID" ON "ProductsSubCategories" ("StatusID");

CREATE INDEX "IX_ProductsSubCategories_SubCategoryID" ON "ProductsSubCategories" ("SubCategoryID");

CREATE INDEX "IX_Units_CreatedUserID" ON "Units" ("CreatedUserID");

CREATE INDEX "IX_Units_DeletedUserID" ON "Units" ("DeletedUserID");

CREATE INDEX "IX_Units_EditUserID" ON "Units" ("EditUserID");

CREATE UNIQUE INDEX "IX_Units_LongDescription" ON "Units" ("LongDescription");

CREATE UNIQUE INDEX "IX_Units_ShortDescription" ON "Units" ("ShortDescription");

CREATE INDEX "IX_Units_StatusID" ON "Units" ("StatusID");

ALTER TABLE "Brands" ADD CONSTRAINT "FK_Brands_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID");

ALTER TABLE "Brands" ADD CONSTRAINT "FK_Brands_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251108154950_UnitCurrencyProduct', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "Brands" ADD "Image" text;

CREATE TABLE "ProductsColors" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductID" integer NOT NULL,
    "ColorCode" character varying(6),
    "ColorName" character varying(300) NOT NULL,
    "IsCover" boolean NOT NULL,
    "StatusID" character varying(1) NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    "EditUserID" integer,
    "EditDate" timestamp with time zone,
    "DeletedUserID" integer,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_ProductsColors" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_ProductsColors_Products_ProductID" FOREIGN KEY ("ProductID") REFERENCES "Products" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductsColors_Statuses_StatusID" FOREIGN KEY ("StatusID") REFERENCES "Statuses" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductsColors_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductsColors_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID"),
    CONSTRAINT "FK_ProductsColors_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID")
);

CREATE TABLE "Size" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" character varying(100) NOT NULL,
    "Rank" integer NOT NULL,
    "StatusID" character varying(1) NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    "EditUserID" integer,
    "EditDate" timestamp with time zone,
    "DeletedUserID" integer,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Size" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Size_Statuses_StatusID" FOREIGN KEY ("StatusID") REFERENCES "Statuses" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Size_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Size_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID"),
    CONSTRAINT "FK_Size_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID")
);

CREATE TABLE "ProductsImages" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductID" integer NOT NULL,
    "ProductColorID" integer NOT NULL,
    "SmallImage" text,
    "OriginalImage" text,
    "IsInitial" boolean NOT NULL,
    "StatusID" character varying(1) NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    "EditUserID" integer,
    "EditDate" timestamp with time zone,
    "DeletedUserID" integer,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_ProductsImages" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_ProductsImages_ProductsColors_ProductColorID" FOREIGN KEY ("ProductColorID") REFERENCES "ProductsColors" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductsImages_Products_ProductID" FOREIGN KEY ("ProductID") REFERENCES "Products" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductsImages_Statuses_StatusID" FOREIGN KEY ("StatusID") REFERENCES "Statuses" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductsImages_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductsImages_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID"),
    CONSTRAINT "FK_ProductsImages_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID")
);

CREATE TABLE "Prices" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductID" integer NOT NULL,
    "SizeID" integer NOT NULL,
    "CountryID" integer NOT NULL,
    "CurrencyID" integer NOT NULL,
    "Amount" numeric(12,2) NOT NULL,
    "StatusID" character varying(1) NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    "EditUserID" integer,
    "EditDate" timestamp with time zone,
    "DeletedUserID" integer,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Prices" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Prices_Countries_CountryID" FOREIGN KEY ("CountryID") REFERENCES "Countries" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Prices_Currencies_CurrencyID" FOREIGN KEY ("CurrencyID") REFERENCES "Currencies" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Prices_Products_ProductID" FOREIGN KEY ("ProductID") REFERENCES "Products" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Prices_Size_SizeID" FOREIGN KEY ("SizeID") REFERENCES "Size" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Prices_Statuses_StatusID" FOREIGN KEY ("StatusID") REFERENCES "Statuses" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Prices_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Prices_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID"),
    CONSTRAINT "FK_Prices_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID")
);

CREATE TABLE "ProductsSizes" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductID" integer NOT NULL,
    "SizeID" integer NOT NULL,
    "Sale" numeric(12,2) NOT NULL,
    "Raise" numeric(12,2) NOT NULL,
    "StatusID" character varying(1) NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    "EditUserID" integer,
    "EditDate" timestamp with time zone,
    "DeletedUserID" integer,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_ProductsSizes" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_ProductsSizes_Products_ProductID" FOREIGN KEY ("ProductID") REFERENCES "Products" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductsSizes_Size_SizeID" FOREIGN KEY ("SizeID") REFERENCES "Size" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductsSizes_Statuses_StatusID" FOREIGN KEY ("StatusID") REFERENCES "Statuses" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductsSizes_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductsSizes_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID"),
    CONSTRAINT "FK_ProductsSizes_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID")
);

CREATE TABLE "Stocks" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductID" integer NOT NULL,
    "SizeID" integer NOT NULL,
    "ProductColorID" integer NOT NULL,
    "Barcode" character varying(50) NOT NULL,
    "Quantity" numeric(12,2) NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    "EditUserID" integer,
    "EditDate" timestamp with time zone,
    "DeletedUserID" integer,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Stocks" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Stocks_ProductsColors_ProductColorID" FOREIGN KEY ("ProductColorID") REFERENCES "ProductsColors" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Stocks_Products_ProductID" FOREIGN KEY ("ProductID") REFERENCES "Products" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Stocks_Size_SizeID" FOREIGN KEY ("SizeID") REFERENCES "Size" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Stocks_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Stocks_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID"),
    CONSTRAINT "FK_Stocks_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID")
);

CREATE INDEX "IX_Prices_CountryID" ON "Prices" ("CountryID");

CREATE INDEX "IX_Prices_CreatedUserID" ON "Prices" ("CreatedUserID");

CREATE INDEX "IX_Prices_CurrencyID" ON "Prices" ("CurrencyID");

CREATE INDEX "IX_Prices_DeletedUserID" ON "Prices" ("DeletedUserID");

CREATE INDEX "IX_Prices_EditUserID" ON "Prices" ("EditUserID");

CREATE INDEX "IX_Prices_ProductID" ON "Prices" ("ProductID");

CREATE INDEX "IX_Prices_SizeID" ON "Prices" ("SizeID");

CREATE INDEX "IX_Prices_StatusID" ON "Prices" ("StatusID");

CREATE INDEX "IX_ProductsColors_CreatedUserID" ON "ProductsColors" ("CreatedUserID");

CREATE INDEX "IX_ProductsColors_DeletedUserID" ON "ProductsColors" ("DeletedUserID");

CREATE INDEX "IX_ProductsColors_EditUserID" ON "ProductsColors" ("EditUserID");

CREATE INDEX "IX_ProductsColors_ProductID" ON "ProductsColors" ("ProductID");

CREATE INDEX "IX_ProductsColors_StatusID" ON "ProductsColors" ("StatusID");

CREATE INDEX "IX_ProductsImages_CreatedUserID" ON "ProductsImages" ("CreatedUserID");

CREATE INDEX "IX_ProductsImages_DeletedUserID" ON "ProductsImages" ("DeletedUserID");

CREATE INDEX "IX_ProductsImages_EditUserID" ON "ProductsImages" ("EditUserID");

CREATE INDEX "IX_ProductsImages_ProductColorID" ON "ProductsImages" ("ProductColorID");

CREATE INDEX "IX_ProductsImages_ProductID" ON "ProductsImages" ("ProductID");

CREATE INDEX "IX_ProductsImages_StatusID" ON "ProductsImages" ("StatusID");

CREATE INDEX "IX_ProductsSizes_CreatedUserID" ON "ProductsSizes" ("CreatedUserID");

CREATE INDEX "IX_ProductsSizes_DeletedUserID" ON "ProductsSizes" ("DeletedUserID");

CREATE INDEX "IX_ProductsSizes_EditUserID" ON "ProductsSizes" ("EditUserID");

CREATE INDEX "IX_ProductsSizes_ProductID" ON "ProductsSizes" ("ProductID");

CREATE INDEX "IX_ProductsSizes_SizeID" ON "ProductsSizes" ("SizeID");

CREATE INDEX "IX_ProductsSizes_StatusID" ON "ProductsSizes" ("StatusID");

CREATE INDEX "IX_Size_CreatedUserID" ON "Size" ("CreatedUserID");

CREATE INDEX "IX_Size_DeletedUserID" ON "Size" ("DeletedUserID");

CREATE UNIQUE INDEX "IX_Size_Description" ON "Size" ("Description");

CREATE INDEX "IX_Size_EditUserID" ON "Size" ("EditUserID");

CREATE INDEX "IX_Size_StatusID" ON "Size" ("StatusID");

CREATE INDEX "IX_Stocks_CreatedUserID" ON "Stocks" ("CreatedUserID");

CREATE INDEX "IX_Stocks_DeletedUserID" ON "Stocks" ("DeletedUserID");

CREATE INDEX "IX_Stocks_EditUserID" ON "Stocks" ("EditUserID");

CREATE INDEX "IX_Stocks_ProductColorID" ON "Stocks" ("ProductColorID");

CREATE INDEX "IX_Stocks_ProductID" ON "Stocks" ("ProductID");

CREATE INDEX "IX_Stocks_SizeID" ON "Stocks" ("SizeID");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251108171419_AllProductRelationsInfo', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "ProductsColors" ADD "ColorID" integer NOT NULL DEFAULT 0;

CREATE TABLE "Colors" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(6),
    "Name" character varying(300) NOT NULL,
    "StatusID" character varying(1) NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "EditUserID" integer NOT NULL,
    "DeletedUserID" integer NOT NULL,
    CONSTRAINT "PK_Colors" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Colors_Statuses_StatusID" FOREIGN KEY ("StatusID") REFERENCES "Statuses" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Colors_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Colors_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Colors_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE
);

CREATE INDEX "IX_ProductsColors_ColorID" ON "ProductsColors" ("ColorID");

CREATE UNIQUE INDEX "IX_Colors_Code" ON "Colors" ("Code");

CREATE INDEX "IX_Colors_CreatedUserID" ON "Colors" ("CreatedUserID");

CREATE INDEX "IX_Colors_DeletedUserID" ON "Colors" ("DeletedUserID");

CREATE INDEX "IX_Colors_EditUserID" ON "Colors" ("EditUserID");

CREATE UNIQUE INDEX "IX_Colors_Name" ON "Colors" ("Name");

CREATE INDEX "IX_Colors_StatusID" ON "Colors" ("StatusID");

ALTER TABLE "ProductsColors" ADD CONSTRAINT "FK_ProductsColors_Colors_ColorID" FOREIGN KEY ("ColorID") REFERENCES "Colors" ("ID") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251108173819_ColorsTable', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "ProductsColors" DROP COLUMN "ColorCode";

ALTER TABLE "ProductsColors" DROP COLUMN "ColorName";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251108183435_RemoveColorFieldsFromProductColor', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "ProductsImages" DROP CONSTRAINT "FK_ProductsImages_ProductsColors_ProductColorID";

ALTER TABLE "ProductsImages" RENAME COLUMN "ProductColorID" TO "ColorID";

ALTER INDEX "IX_ProductsImages_ProductColorID" RENAME TO "IX_ProductsImages_ColorID";

ALTER TABLE "ProductsImages" ADD CONSTRAINT "FK_ProductsImages_Colors_ColorID" FOREIGN KEY ("ColorID") REFERENCES "Colors" ("ID") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251108185657_RemoveProductColorFromProductImages', '8.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE "Carts" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ClientID" integer NOT NULL,
    "ProductID" integer NOT NULL,
    "SizeID" integer NOT NULL,
    "ColorID" integer NOT NULL,
    "Quantity" numeric(12,2) NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    "EditUserID" integer,
    "EditDate" timestamp with time zone,
    "DeletedUserID" integer,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Carts" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Carts_Clients_ClientID" FOREIGN KEY ("ClientID") REFERENCES "Clients" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Carts_Colors_ColorID" FOREIGN KEY ("ColorID") REFERENCES "Colors" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Carts_Products_ProductID" FOREIGN KEY ("ProductID") REFERENCES "Products" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Carts_Size_SizeID" FOREIGN KEY ("SizeID") REFERENCES "Size" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Carts_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Carts_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID"),
    CONSTRAINT "FK_Carts_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID")
);

CREATE INDEX "IX_Carts_ClientID" ON "Carts" ("ClientID");

CREATE INDEX "IX_Carts_ColorID" ON "Carts" ("ColorID");

CREATE INDEX "IX_Carts_CreatedUserID" ON "Carts" ("CreatedUserID");

CREATE INDEX "IX_Carts_DeletedUserID" ON "Carts" ("DeletedUserID");

CREATE INDEX "IX_Carts_EditUserID" ON "Carts" ("EditUserID");

CREATE INDEX "IX_Carts_ProductID" ON "Carts" ("ProductID");

CREATE INDEX "IX_Carts_SizeID" ON "Carts" ("SizeID");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251108190258_CreateCartTable', '8.0.20');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251108191134_RemoveIdendityCountryID', '8.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE "GetWays" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "MerchantID" character varying(50) NOT NULL,
    "MerchantPassword" text NOT NULL,
    "Mode" character varying(4) NOT NULL,
    "Url" character varying(150) NOT NULL,
    "StatusID" character varying(1) NOT NULL,
    CONSTRAINT "PK_GetWays" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_GetWays_Statuses_StatusID" FOREIGN KEY ("StatusID") REFERENCES "Statuses" ("ID") ON DELETE CASCADE
);

CREATE INDEX "IX_GetWays_StatusID" ON "GetWays" ("StatusID");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251108193055_AddGateWaysTable', '8.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE "TrackingOrderStatuses" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" char(3) NOT NULL,
    "Description" character varying(50) NOT NULL,
    CONSTRAINT "PK_TrackingOrderStatuses" PRIMARY KEY ("ID")
);

CREATE TABLE "Orders" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(50) NOT NULL,
    "PaymentCode" character varying(50),
    "Date" timestamp with time zone NOT NULL,
    "ClientID" integer NOT NULL,
    "ClientAddressID" integer NOT NULL,
    "PromoCode" text NOT NULL,
    "PromoCodePercentage" integer NOT NULL,
    "Tax" numeric(12,2) NOT NULL,
    "ShippingCost" numeric(12,2) NOT NULL,
    "MoneyTransferFees" numeric(12,2) NOT NULL,
    "CurrencyID" integer NOT NULL,
    "VAT" numeric(12,2) NOT NULL,
    "VATAmount" numeric(12,2) NOT NULL,
    "GobalDiscount" numeric(12,2) NOT NULL,
    "CurrentTrackingOrderStatusID" integer NOT NULL,
    "CurrentTrackingOrderDate" date NOT NULL,
    "EditUserID" integer,
    "EditDate" timestamp with time zone,
    "DeletedUserID" integer,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Orders_ClientAddresses_ClientAddressID" FOREIGN KEY ("ClientAddressID") REFERENCES "ClientAddresses" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Orders_Clients_ClientID" FOREIGN KEY ("ClientID") REFERENCES "Clients" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Orders_Currencies_CurrencyID" FOREIGN KEY ("CurrencyID") REFERENCES "Currencies" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Orders_TrackingOrderStatuses_CurrentTrackingOrderStatusID" FOREIGN KEY ("CurrentTrackingOrderStatusID") REFERENCES "TrackingOrderStatuses" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Orders_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID"),
    CONSTRAINT "FK_Orders_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID")
);

CREATE TABLE "OrderProducts" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderID" integer NOT NULL,
    "ProductID" integer NOT NULL,
    "SizeID" integer NOT NULL,
    "ColorID" integer NOT NULL,
    "Quantity" numeric(12,2) NOT NULL,
    "QuantityPending" numeric(12,2) NOT NULL,
    "QuantityDelivered" numeric(12,2) NOT NULL,
    "QuantityCancelled" numeric(12,2) NOT NULL,
    "Price" numeric(12,2) NOT NULL,
    "Discount" numeric(12,2) NOT NULL,
    "VATAmount" numeric(12,2) NOT NULL,
    "PriceNet" numeric(12,2) NOT NULL,
    "SubTotal" numeric(12,2) NOT NULL,
    "CancellationReason" text,
    "CreationDate" timestamp with time zone NOT NULL,
    "EditUserID" integer,
    "EditDate" timestamp with time zone,
    "DeletedUserID" integer,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_OrderProducts" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_OrderProducts_Colors_ColorID" FOREIGN KEY ("ColorID") REFERENCES "Colors" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_OrderProducts_Orders_OrderID" FOREIGN KEY ("OrderID") REFERENCES "Orders" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_OrderProducts_Products_ProductID" FOREIGN KEY ("ProductID") REFERENCES "Products" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_OrderProducts_Size_SizeID" FOREIGN KEY ("SizeID") REFERENCES "Size" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_OrderProducts_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID"),
    CONSTRAINT "FK_OrderProducts_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID")
);

CREATE TABLE "TrackingOrders" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderID" integer NOT NULL,
    "TrackingOrderStatusID" integer NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TrackingOrders" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_TrackingOrders_Orders_OrderID" FOREIGN KEY ("OrderID") REFERENCES "Orders" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_TrackingOrders_TrackingOrderStatuses_TrackingOrderStatusID" FOREIGN KEY ("TrackingOrderStatusID") REFERENCES "TrackingOrderStatuses" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_TrackingOrders_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE
);

CREATE INDEX "IX_OrderProducts_ColorID" ON "OrderProducts" ("ColorID");

CREATE INDEX "IX_OrderProducts_DeletedUserID" ON "OrderProducts" ("DeletedUserID");

CREATE INDEX "IX_OrderProducts_EditUserID" ON "OrderProducts" ("EditUserID");

CREATE INDEX "IX_OrderProducts_OrderID" ON "OrderProducts" ("OrderID");

CREATE INDEX "IX_OrderProducts_ProductID" ON "OrderProducts" ("ProductID");

CREATE INDEX "IX_OrderProducts_SizeID" ON "OrderProducts" ("SizeID");

CREATE INDEX "IX_Orders_ClientAddressID" ON "Orders" ("ClientAddressID");

CREATE INDEX "IX_Orders_ClientID" ON "Orders" ("ClientID");

CREATE UNIQUE INDEX "IX_Orders_Code" ON "Orders" ("Code");

CREATE INDEX "IX_Orders_CurrencyID" ON "Orders" ("CurrencyID");

CREATE INDEX "IX_Orders_CurrentTrackingOrderStatusID" ON "Orders" ("CurrentTrackingOrderStatusID");

CREATE INDEX "IX_Orders_DeletedUserID" ON "Orders" ("DeletedUserID");

CREATE INDEX "IX_Orders_EditUserID" ON "Orders" ("EditUserID");

CREATE UNIQUE INDEX "IX_Orders_PaymentCode" ON "Orders" ("PaymentCode");

CREATE INDEX "IX_TrackingOrders_CreatedUserID" ON "TrackingOrders" ("CreatedUserID");

CREATE INDEX "IX_TrackingOrders_OrderID" ON "TrackingOrders" ("OrderID");

CREATE INDEX "IX_TrackingOrders_TrackingOrderStatusID" ON "TrackingOrders" ("TrackingOrderStatusID");

CREATE UNIQUE INDEX "IX_TrackingOrderStatuses_Code" ON "TrackingOrderStatuses" ("Code");

CREATE UNIQUE INDEX "IX_TrackingOrderStatuses_Description" ON "TrackingOrderStatuses" ("Description");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251108212852_CreateOrders', '8.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE "POSStocks" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Barcode" character varying(50) NOT NULL,
    "Name" character varying(255) NOT NULL,
    "Quantity" numeric(12,2) NOT NULL,
    CONSTRAINT "PK_POSStocks" PRIMARY KEY ("ID")
);

CREATE TABLE "ProductsBestSeller" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductID" integer NOT NULL,
    "SizeID" integer NOT NULL,
    "ColorID" integer NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ProductsBestSeller" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_ProductsBestSeller_Colors_ColorID" FOREIGN KEY ("ColorID") REFERENCES "Colors" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductsBestSeller_Products_ProductID" FOREIGN KEY ("ProductID") REFERENCES "Products" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductsBestSeller_Size_SizeID" FOREIGN KEY ("SizeID") REFERENCES "Size" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductsBestSeller_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE
);

CREATE TABLE "ProductsRecentlyViewed" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ClientID" integer NOT NULL,
    "ProductID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ProductsRecentlyViewed" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_ProductsRecentlyViewed_Clients_ClientID" FOREIGN KEY ("ClientID") REFERENCES "Clients" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductsRecentlyViewed_Products_ProductID" FOREIGN KEY ("ProductID") REFERENCES "Products" ("ID") ON DELETE CASCADE
);

CREATE TABLE "ProductsWishList" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ClientID" integer NOT NULL,
    "ProductID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ProductsWishList" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_ProductsWishList_Clients_ClientID" FOREIGN KEY ("ClientID") REFERENCES "Clients" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductsWishList_Products_ProductID" FOREIGN KEY ("ProductID") REFERENCES "Products" ("ID") ON DELETE CASCADE
);

CREATE TABLE "Services" (
    "ID" text NOT NULL,
    "Text" text NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    "EditUserID" integer,
    "EditDate" timestamp with time zone,
    CONSTRAINT "PK_Services" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Services_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Services_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID")
);

CREATE TABLE "SocialMedias" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(10) NOT NULL,
    "Description" character varying(50) NOT NULL,
    "Icon" character varying(100) NOT NULL,
    "Rank" integer NOT NULL,
    CONSTRAINT "PK_SocialMedias" PRIMARY KEY ("ID")
);

CREATE TABLE "Subscriptions" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" character varying(300) NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Subscriptions" PRIMARY KEY ("ID")
);

CREATE UNIQUE INDEX "IX_POSStocks_Barcode" ON "POSStocks" ("Barcode");

CREATE INDEX "IX_ProductsBestSeller_ColorID" ON "ProductsBestSeller" ("ColorID");

CREATE INDEX "IX_ProductsBestSeller_CreatedUserID" ON "ProductsBestSeller" ("CreatedUserID");

CREATE INDEX "IX_ProductsBestSeller_ProductID" ON "ProductsBestSeller" ("ProductID");

CREATE INDEX "IX_ProductsBestSeller_SizeID" ON "ProductsBestSeller" ("SizeID");

CREATE INDEX "IX_ProductsRecentlyViewed_ClientID" ON "ProductsRecentlyViewed" ("ClientID");

CREATE INDEX "IX_ProductsRecentlyViewed_ProductID" ON "ProductsRecentlyViewed" ("ProductID");

CREATE INDEX "IX_ProductsWishList_ClientID" ON "ProductsWishList" ("ClientID");

CREATE INDEX "IX_ProductsWishList_ProductID" ON "ProductsWishList" ("ProductID");

CREATE INDEX "IX_Services_CreatedUserID" ON "Services" ("CreatedUserID");

CREATE INDEX "IX_Services_EditUserID" ON "Services" ("EditUserID");

CREATE UNIQUE INDEX "IX_SocialMedias_Code" ON "SocialMedias" ("Code");

CREATE UNIQUE INDEX "IX_SocialMedias_Description" ON "SocialMedias" ("Description");

CREATE UNIQUE INDEX "IX_Subscriptions_Email" ON "Subscriptions" ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251108222203_CreateExtraInformationTable', '8.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE "Notifications" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Date" date NOT NULL,
    "ClientID" integer NOT NULL,
    "IsRead" boolean NOT NULL,
    "Message" text NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Notifications_Clients_ClientID" FOREIGN KEY ("ClientID") REFERENCES "Clients" ("ID") ON DELETE CASCADE
);

CREATE INDEX "IX_Notifications_ClientID" ON "Notifications" ("ClientID");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251109165923_NotificationsTable', '8.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE "Banners" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" character varying(50) NOT NULL,
    "Image" text NOT NULL,
    "Sentence" text,
    "Link" text,
    "StatusID" character varying(1) NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    "EditUserID" integer,
    "EditDate" timestamp with time zone,
    "DeletedUserID" integer,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Banners" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Banners_Statuses_StatusID" FOREIGN KEY ("StatusID") REFERENCES "Statuses" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Banners_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Banners_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID"),
    CONSTRAINT "FK_Banners_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID")
);

CREATE TABLE "BannersMobiles" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Image" text NOT NULL,
    "CategoryID" integer NOT NULL,
    "SubCategoryID" integer NOT NULL,
    "ProductID" integer NOT NULL,
    "StatusID" character varying(1) NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    "EditUserID" integer,
    "EditDate" timestamp with time zone,
    "DeletedUserID" integer,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_BannersMobiles" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_BannersMobiles_Categories_CategoryID" FOREIGN KEY ("CategoryID") REFERENCES "Categories" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_BannersMobiles_Products_ProductID" FOREIGN KEY ("ProductID") REFERENCES "Products" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_BannersMobiles_Statuses_StatusID" FOREIGN KEY ("StatusID") REFERENCES "Statuses" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_BannersMobiles_SubCategories_SubCategoryID" FOREIGN KEY ("SubCategoryID") REFERENCES "SubCategories" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_BannersMobiles_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_BannersMobiles_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID"),
    CONSTRAINT "FK_BannersMobiles_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID")
);

CREATE TABLE "BannersPages" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(10) NOT NULL,
    "Name" character varying(50) NOT NULL,
    "Image" text NOT NULL,
    "Link" text NOT NULL,
    "StatusID" character varying(1) NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    "EditUserID" integer,
    "EditDate" timestamp with time zone,
    "DeletedUserID" integer,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_BannersPages" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_BannersPages_Statuses_StatusID" FOREIGN KEY ("StatusID") REFERENCES "Statuses" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_BannersPages_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_BannersPages_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID"),
    CONSTRAINT "FK_BannersPages_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID")
);

CREATE INDEX "IX_Banners_CreatedUserID" ON "Banners" ("CreatedUserID");

CREATE INDEX "IX_Banners_DeletedUserID" ON "Banners" ("DeletedUserID");

CREATE INDEX "IX_Banners_EditUserID" ON "Banners" ("EditUserID");

CREATE INDEX "IX_Banners_StatusID" ON "Banners" ("StatusID");

CREATE INDEX "IX_BannersMobiles_CategoryID" ON "BannersMobiles" ("CategoryID");

CREATE INDEX "IX_BannersMobiles_CreatedUserID" ON "BannersMobiles" ("CreatedUserID");

CREATE INDEX "IX_BannersMobiles_DeletedUserID" ON "BannersMobiles" ("DeletedUserID");

CREATE INDEX "IX_BannersMobiles_EditUserID" ON "BannersMobiles" ("EditUserID");

CREATE INDEX "IX_BannersMobiles_ProductID" ON "BannersMobiles" ("ProductID");

CREATE INDEX "IX_BannersMobiles_StatusID" ON "BannersMobiles" ("StatusID");

CREATE INDEX "IX_BannersMobiles_SubCategoryID" ON "BannersMobiles" ("SubCategoryID");

CREATE UNIQUE INDEX "IX_BannersPages_Code" ON "BannersPages" ("Code");

CREATE INDEX "IX_BannersPages_CreatedUserID" ON "BannersPages" ("CreatedUserID");

CREATE INDEX "IX_BannersPages_DeletedUserID" ON "BannersPages" ("DeletedUserID");

CREATE INDEX "IX_BannersPages_EditUserID" ON "BannersPages" ("EditUserID");

CREATE UNIQUE INDEX "IX_BannersPages_Name" ON "BannersPages" ("Name");

CREATE INDEX "IX_BannersPages_StatusID" ON "BannersPages" ("StatusID");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251109174955_AllBannersTable', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "Clients" ADD "Approvement" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251114164208_AddApprovmentToClient', '8.0.20');

COMMIT;

START TRANSACTION;

DROP INDEX "IX_Users_Username";

DROP INDEX "IX_Units_LongDescription";

DROP INDEX "IX_Units_ShortDescription";

DROP INDEX "IX_TrackingOrderStatuses_Code";

DROP INDEX "IX_TrackingOrderStatuses_Description";

DROP INDEX "IX_Subscriptions_Email";

DROP INDEX "IX_SubCategories_Description";

DROP INDEX "IX_Size_Description";

DROP INDEX "IX_Roles_Description";

DROP INDEX "IX_Products_Code";

DROP INDEX "IX_Products_Name";

DROP INDEX "IX_POSStocks_Barcode";

DROP INDEX "IX_Permissions_Code";

DROP INDEX "IX_Permissions_Description";

DROP INDEX "IX_Orders_Code";

DROP INDEX "IX_Orders_PaymentCode";

DROP INDEX "IX_Currencies_Code";

DROP INDEX "IX_Currencies_Description";

DROP INDEX "IX_Countries_Name";

DROP INDEX "IX_Colors_Code";

DROP INDEX "IX_Colors_Name";

DROP INDEX "IX_Categories_Description";

DROP INDEX "IX_Brands_Name";

DROP INDEX "IX_BannersPages_Code";

DROP INDEX "IX_BannersPages_Name";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251122153156_removeuniquefromalltables', '8.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE "GroupTypes" (
    "ID" character varying(3) NOT NULL,
    "Description" character varying(50) NOT NULL,
    CONSTRAINT "PK_GroupTypes" PRIMARY KEY ("ID")
);

CREATE TABLE "Groups" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "Summary" text,
    "Image" text,
    "ShowHome" boolean NOT NULL,
    "Rank" integer NOT NULL,
    "TypeID" character varying(3) NOT NULL,
    "StatusID" character varying(1) NOT NULL,
    "CreatedUserID" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    "EditUserID" integer,
    "EditDate" timestamp with time zone,
    "DeletedUserID" integer,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Groups" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Groups_GroupTypes_TypeID" FOREIGN KEY ("TypeID") REFERENCES "GroupTypes" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Groups_Statuses_StatusID" FOREIGN KEY ("StatusID") REFERENCES "Statuses" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Groups_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Groups_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID"),
    CONSTRAINT "FK_Groups_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID")
);

CREATE INDEX "IX_Groups_CreatedUserID" ON "Groups" ("CreatedUserID");

CREATE INDEX "IX_Groups_DeletedUserID" ON "Groups" ("DeletedUserID");

CREATE INDEX "IX_Groups_EditUserID" ON "Groups" ("EditUserID");

CREATE INDEX "IX_Groups_StatusID" ON "Groups" ("StatusID");

CREATE INDEX "IX_Groups_TypeID" ON "Groups" ("TypeID");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251127131657_CreateTableGroupGroupType', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "Products" ADD "GroupID" integer NOT NULL DEFAULT 0;

CREATE INDEX "IX_Products_GroupID" ON "Products" ("GroupID");

ALTER TABLE "Products" ADD CONSTRAINT "FK_Products_Groups_GroupID" FOREIGN KEY ("GroupID") REFERENCES "Groups" ("ID") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251127132548_ChangeBrandIDToGroupIDInProduct', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "Products" DROP CONSTRAINT "FK_Products_Brands_BrandID";

DROP INDEX "IX_Products_BrandID";

ALTER TABLE "Products" DROP COLUMN "BrandID";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251127133258_RemoveBrandFromProducts', '8.0.20');

COMMIT;

START TRANSACTION;

DROP TABLE "Brands";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251127134526_RemoveBrand', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "Products" ALTER COLUMN "VideoUrl" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251206114344_ProductSetVideoUrlToNull', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "Colors" DROP CONSTRAINT "FK_Colors_Users_DeletedUserID";

ALTER TABLE "Colors" DROP CONSTRAINT "FK_Colors_Users_EditUserID";

ALTER TABLE "Colors" ALTER COLUMN "EditUserID" DROP NOT NULL;

ALTER TABLE "Colors" ALTER COLUMN "DeletedUserID" DROP NOT NULL;

ALTER TABLE "Colors" ADD "CreationDate" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Colors" ADD "DeletedDate" timestamp with time zone;

ALTER TABLE "Colors" ADD "EditDate" timestamp with time zone;

ALTER TABLE "Colors" ADD CONSTRAINT "FK_Colors_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID");

ALTER TABLE "Colors" ADD CONSTRAINT "FK_Colors_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251213110416_CreateEditDeletedateToColor', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "Countries" ADD "Flag" character varying(500);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251213125717_AddFlagToCountry', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "Currencies" ADD "CountryID" integer;

CREATE INDEX "IX_Currencies_CountryID" ON "Currencies" ("CountryID");

ALTER TABLE "Currencies" ADD CONSTRAINT "FK_Currencies_Countries_CountryID" FOREIGN KEY ("CountryID") REFERENCES "Countries" ("ID");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251213145449_AddCountryIDToCurrency', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "TrackingOrderStatuses" ALTER COLUMN "Description" TYPE text;

ALTER TABLE "TrackingOrderStatuses" ALTER COLUMN "Code" TYPE text;

ALTER TABLE "CurrenciesConversion" ALTER COLUMN "Operator" TYPE character varying(3);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251213162238_SetOperationToStringCurrencyConversion', '8.0.20');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251213163708_RemoveStringLengthIDsCurrencyConversion', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "Prices" ADD "AmountNet" numeric(12,2) NOT NULL DEFAULT 0.0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251213194116_AddAmountNetToPrice', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "Colors" ADD "IsCustom" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251224185455_AddIsCustomToColorTable', '8.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "Carts" DROP CONSTRAINT "FK_Carts_Size_SizeID";

ALTER TABLE "OrderProducts" DROP CONSTRAINT "FK_OrderProducts_Size_SizeID";

ALTER TABLE "Prices" DROP CONSTRAINT "FK_Prices_Size_SizeID";

ALTER TABLE "ProductsBestSeller" DROP CONSTRAINT "FK_ProductsBestSeller_Size_SizeID";

ALTER TABLE "ProductsSizes" DROP CONSTRAINT "FK_ProductsSizes_Size_SizeID";

ALTER TABLE "Size" DROP CONSTRAINT "FK_Size_Statuses_StatusID";

ALTER TABLE "Size" DROP CONSTRAINT "FK_Size_Users_CreatedUserID";

ALTER TABLE "Size" DROP CONSTRAINT "FK_Size_Users_DeletedUserID";

ALTER TABLE "Size" DROP CONSTRAINT "FK_Size_Users_EditUserID";

ALTER TABLE "Stocks" DROP CONSTRAINT "FK_Stocks_Size_SizeID";

ALTER TABLE "Size" DROP CONSTRAINT "PK_Size";

ALTER TABLE "Size" RENAME TO "Sizes";

ALTER INDEX "IX_Size_StatusID" RENAME TO "IX_Sizes_StatusID";

ALTER INDEX "IX_Size_EditUserID" RENAME TO "IX_Sizes_EditUserID";

ALTER INDEX "IX_Size_DeletedUserID" RENAME TO "IX_Sizes_DeletedUserID";

ALTER INDEX "IX_Size_CreatedUserID" RENAME TO "IX_Sizes_CreatedUserID";

ALTER TABLE "Sizes" ADD CONSTRAINT "PK_Sizes" PRIMARY KEY ("ID");

ALTER TABLE "Carts" ADD CONSTRAINT "FK_Carts_Sizes_SizeID" FOREIGN KEY ("SizeID") REFERENCES "Sizes" ("ID") ON DELETE CASCADE;

ALTER TABLE "OrderProducts" ADD CONSTRAINT "FK_OrderProducts_Sizes_SizeID" FOREIGN KEY ("SizeID") REFERENCES "Sizes" ("ID") ON DELETE CASCADE;

ALTER TABLE "Prices" ADD CONSTRAINT "FK_Prices_Sizes_SizeID" FOREIGN KEY ("SizeID") REFERENCES "Sizes" ("ID") ON DELETE CASCADE;

ALTER TABLE "ProductsBestSeller" ADD CONSTRAINT "FK_ProductsBestSeller_Sizes_SizeID" FOREIGN KEY ("SizeID") REFERENCES "Sizes" ("ID") ON DELETE CASCADE;

ALTER TABLE "ProductsSizes" ADD CONSTRAINT "FK_ProductsSizes_Sizes_SizeID" FOREIGN KEY ("SizeID") REFERENCES "Sizes" ("ID") ON DELETE CASCADE;

ALTER TABLE "Sizes" ADD CONSTRAINT "FK_Sizes_Statuses_StatusID" FOREIGN KEY ("StatusID") REFERENCES "Statuses" ("ID") ON DELETE CASCADE;

ALTER TABLE "Sizes" ADD CONSTRAINT "FK_Sizes_Users_CreatedUserID" FOREIGN KEY ("CreatedUserID") REFERENCES "Users" ("ID") ON DELETE CASCADE;

ALTER TABLE "Sizes" ADD CONSTRAINT "FK_Sizes_Users_DeletedUserID" FOREIGN KEY ("DeletedUserID") REFERENCES "Users" ("ID");

ALTER TABLE "Sizes" ADD CONSTRAINT "FK_Sizes_Users_EditUserID" FOREIGN KEY ("EditUserID") REFERENCES "Users" ("ID");

ALTER TABLE "Stocks" ADD CONSTRAINT "FK_Stocks_Sizes_SizeID" FOREIGN KEY ("SizeID") REFERENCES "Sizes" ("ID") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251227163310_ChangeFromSizeToSizes', '8.0.20');

COMMIT;


