// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TsunamiTattooSupply.Data;

#nullable disable

namespace TsunamiTattooSupply.Migrations
{
    [DbContext(typeof(TsunamiDbContext))]
    [Migration("20251108185657_RemoveProductColorFromProductImages")]
    partial class RemoveProductColorFromProductImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TsunamiTattooSupply.Models.Brand", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CreatedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EditUserID")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowHome")
                        .HasColumnType("boolean");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasColumnType("character varying(1)");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("EditUserID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StatusID");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("AD_Image1")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AD_Image2")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AD_Image3")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BannerImage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("CreatedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EditUserID")
                        .HasColumnType("integer");

                    b.Property<string>("MobileImage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasColumnType("character varying(1)");

                    b.Property<string>("WebImage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("ID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.HasIndex("EditUserID");

                    b.HasIndex("StatusID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CreatedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("integer");

                    b.Property<string>("DeviceToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EditUserID")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordMobile")
                        .HasColumnType("char(10)");

                    b.Property<int>("PhoneCountryID")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ResetPasswordLink")
                        .HasColumnType("text");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("EditUserID");

                    b.HasIndex("PhoneCountryID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.ClientAddress", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ClientID")
                        .HasColumnType("integer");

                    b.Property<int>("CountryID")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedUserID")
                        .HasColumnType("integer");

                    b.Property<int>("DeletedUserID")
                        .HasColumnType("integer");

                    b.Property<int>("EditUserID")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Line1")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Line2")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StateProvince")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasColumnType("character varying(1)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.HasIndex("CountryID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("EditUserID");

                    b.HasIndex("StatusID");

                    b.ToTable("ClientAddresses");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.Color", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<int>("CreatedUserID")
                        .HasColumnType("integer");

                    b.Property<int>("DeletedUserID")
                        .HasColumnType("integer");

                    b.Property<int>("EditUserID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasColumnType("character varying(1)");

                    b.HasKey("ID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("EditUserID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StatusID");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ISO2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("ISO3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<double>("MoneyTransferFees")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Native")
                        .HasColumnType("boolean");

                    b.Property<bool>("Sales")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool>("ShippingCostFixed")
                        .HasColumnType("boolean");

                    b.Property<double>("TotalRange")
                        .HasColumnType("double precision");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.Currency", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("CreatedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EditUserID")
                        .HasColumnType("integer");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasColumnType("character varying(1)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("ID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.HasIndex("EditUserID");

                    b.HasIndex("StatusID");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.CurrencyConversion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CurrencyIDFrom")
                        .HasMaxLength(3)
                        .HasColumnType("integer");

                    b.Property<int>("CurrencyIDTo")
                        .HasMaxLength(3)
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EditUserID")
                        .HasColumnType("integer");

                    b.Property<int>("Operator")
                        .HasMaxLength(3)
                        .HasColumnType("integer");

                    b.Property<decimal>("Rate")
                        .HasColumnType("Decimal(12,2)");

                    b.HasKey("ID");

                    b.HasIndex("CurrencyIDFrom");

                    b.HasIndex("CurrencyIDTo");

                    b.HasIndex("EditUserID");

                    b.ToTable("CurrenciesConversion");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.FilePath", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("FilePaths");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.Permission", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("ID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.Price", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("CountryID")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrencyID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EditUserID")
                        .HasColumnType("integer");

                    b.Property<int>("ProductID")
                        .HasColumnType("integer");

                    b.Property<int>("SizeID")
                        .HasColumnType("integer");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasColumnType("character varying(1)");

                    b.HasKey("ID");

                    b.HasIndex("CountryID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("CurrencyID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("EditUserID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SizeID");

                    b.HasIndex("StatusID");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("BrandID")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CreatedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EditUserID")
                        .HasColumnType("integer");

                    b.Property<bool>("Feature")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("NewArrival")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NewArrivalDateExpiryDate")
                        .HasColumnType("date");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasColumnType("character varying(1)");

                    b.Property<int>("UnitID")
                        .HasColumnType("integer");

                    b.Property<bool>("VAT")
                        .HasColumnType("boolean");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Warranty")
                        .HasColumnType("boolean");

                    b.Property<int>("WarrantyMonths")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("BrandID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("EditUserID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StatusID");

                    b.HasIndex("UnitID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.ProductColor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ColorID")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EditUserID")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCover")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductID")
                        .HasColumnType("integer");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasColumnType("character varying(1)");

                    b.HasKey("ID");

                    b.HasIndex("ColorID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("EditUserID");

                    b.HasIndex("ProductID");

                    b.HasIndex("StatusID");

                    b.ToTable("ProductsColors");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.ProductImage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ColorID")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EditUserID")
                        .HasColumnType("integer");

                    b.Property<bool>("IsInitial")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalImage")
                        .HasColumnType("text");

                    b.Property<int>("ProductID")
                        .HasColumnType("integer");

                    b.Property<string>("SmallImage")
                        .HasColumnType("text");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasColumnType("character varying(1)");

                    b.HasKey("ID");

                    b.HasIndex("ColorID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("EditUserID");

                    b.HasIndex("ProductID");

                    b.HasIndex("StatusID");

                    b.ToTable("ProductsImages");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.ProductSize", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CreatedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EditUserID")
                        .HasColumnType("integer");

                    b.Property<int>("ProductID")
                        .HasColumnType("integer");

                    b.Property<decimal>("Raise")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("Sale")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("SizeID")
                        .HasColumnType("integer");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasColumnType("character varying(1)");

                    b.HasKey("ID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("EditUserID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SizeID");

                    b.HasIndex("StatusID");

                    b.ToTable("ProductsSizes");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.ProductSubCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CreatedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EditUserID")
                        .HasColumnType("integer");

                    b.Property<int>("ProductID")
                        .HasColumnType("integer");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasColumnType("character varying(1)");

                    b.Property<int>("SubCategoryID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("EditUserID");

                    b.HasIndex("ProductID");

                    b.HasIndex("StatusID");

                    b.HasIndex("SubCategoryID");

                    b.ToTable("ProductsSubCategories");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("CreatedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EditUserID")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasColumnType("character varying(1)");

                    b.HasKey("ID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.HasIndex("EditUserID");

                    b.HasIndex("StatusID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.RolePermission", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CreatedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PermissionID")
                        .HasColumnType("integer");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("PermissionID");

                    b.HasIndex("RoleID");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.Size", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CreatedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EditUserID")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasColumnType("character varying(1)");

                    b.HasKey("ID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.HasIndex("EditUserID");

                    b.HasIndex("StatusID");

                    b.ToTable("Size");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.Status", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.Stock", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CreatedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EditUserID")
                        .HasColumnType("integer");

                    b.Property<int>("ProductColorID")
                        .HasColumnType("integer");

                    b.Property<int>("ProductID")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("SizeID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("EditUserID");

                    b.HasIndex("ProductColorID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SizeID");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.SubCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("BannerImage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EditUserID")
                        .HasColumnType("integer");

                    b.Property<string>("MobileImage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasColumnType("character varying(1)");

                    b.Property<string>("WebImage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.HasIndex("EditUserID");

                    b.HasIndex("StatusID");

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.Unit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CreatedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EditUserID")
                        .HasColumnType("integer");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasColumnType("character varying(1)");

                    b.HasKey("ID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("EditUserID");

                    b.HasIndex("LongDescription")
                        .IsUnique();

                    b.HasIndex("ShortDescription")
                        .IsUnique();

                    b.HasIndex("StatusID");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("CreatedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EditUserID")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasColumnType("character varying(1)");

                    b.Property<string>("UserTypeID")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.HasIndex("StatusID");

                    b.HasIndex("UserTypeID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.UserType", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID");

                    b.ToTable("UserTypes");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.Brand", b =>
                {
                    b.HasOne("TsunamiTattooSupply.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID");

                    b.HasOne("TsunamiTattooSupply.Models.User", "EditUser")
                        .WithMany()
                        .HasForeignKey("EditUserID");

                    b.HasOne("TsunamiTattooSupply.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("EditUser");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.Category", b =>
                {
                    b.HasOne("TsunamiTattooSupply.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID");

                    b.HasOne("TsunamiTattooSupply.Models.User", "EditUser")
                        .WithMany()
                        .HasForeignKey("EditUserID");

                    b.HasOne("TsunamiTattooSupply.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("EditUser");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.Client", b =>
                {
                    b.HasOne("TsunamiTattooSupply.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID");

                    b.HasOne("TsunamiTattooSupply.Models.User", "EditUser")
                        .WithMany()
                        .HasForeignKey("EditUserID");

                    b.HasOne("TsunamiTattooSupply.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("PhoneCountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("EditUser");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.ClientAddress", b =>
                {
                    b.HasOne("TsunamiTattooSupply.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "EditUser")
                        .WithMany()
                        .HasForeignKey("EditUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Country");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("EditUser");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.Color", b =>
                {
                    b.HasOne("TsunamiTattooSupply.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "EditUser")
                        .WithMany()
                        .HasForeignKey("EditUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("EditUser");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.Currency", b =>
                {
                    b.HasOne("TsunamiTattooSupply.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID");

                    b.HasOne("TsunamiTattooSupply.Models.User", "EditUser")
                        .WithMany()
                        .HasForeignKey("EditUserID");

                    b.HasOne("TsunamiTattooSupply.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("EditUser");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.CurrencyConversion", b =>
                {
                    b.HasOne("TsunamiTattooSupply.Models.Currency", "CurrencyFrom")
                        .WithMany()
                        .HasForeignKey("CurrencyIDFrom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.Currency", "CurrencyTo")
                        .WithMany()
                        .HasForeignKey("CurrencyIDTo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "EditUser")
                        .WithMany()
                        .HasForeignKey("EditUserID");

                    b.Navigation("CurrencyFrom");

                    b.Navigation("CurrencyTo");

                    b.Navigation("EditUser");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.Price", b =>
                {
                    b.HasOne("TsunamiTattooSupply.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID");

                    b.HasOne("TsunamiTattooSupply.Models.User", "EditUser")
                        .WithMany()
                        .HasForeignKey("EditUserID");

                    b.HasOne("TsunamiTattooSupply.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("CreatedUser");

                    b.Navigation("Currency");

                    b.Navigation("DeletedUser");

                    b.Navigation("EditUser");

                    b.Navigation("Product");

                    b.Navigation("Size");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.Product", b =>
                {
                    b.HasOne("TsunamiTattooSupply.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID");

                    b.HasOne("TsunamiTattooSupply.Models.User", "EditUser")
                        .WithMany()
                        .HasForeignKey("EditUserID");

                    b.HasOne("TsunamiTattooSupply.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("EditUser");

                    b.Navigation("Status");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.ProductColor", b =>
                {
                    b.HasOne("TsunamiTattooSupply.Models.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID");

                    b.HasOne("TsunamiTattooSupply.Models.User", "EditUser")
                        .WithMany()
                        .HasForeignKey("EditUserID");

                    b.HasOne("TsunamiTattooSupply.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("EditUser");

                    b.Navigation("Product");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.ProductImage", b =>
                {
                    b.HasOne("TsunamiTattooSupply.Models.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID");

                    b.HasOne("TsunamiTattooSupply.Models.User", "EditUser")
                        .WithMany()
                        .HasForeignKey("EditUserID");

                    b.HasOne("TsunamiTattooSupply.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("EditUser");

                    b.Navigation("Product");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.ProductSize", b =>
                {
                    b.HasOne("TsunamiTattooSupply.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID");

                    b.HasOne("TsunamiTattooSupply.Models.User", "EditUser")
                        .WithMany()
                        .HasForeignKey("EditUserID");

                    b.HasOne("TsunamiTattooSupply.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("EditUser");

                    b.Navigation("Product");

                    b.Navigation("Size");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.ProductSubCategory", b =>
                {
                    b.HasOne("TsunamiTattooSupply.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID");

                    b.HasOne("TsunamiTattooSupply.Models.User", "EditUser")
                        .WithMany()
                        .HasForeignKey("EditUserID");

                    b.HasOne("TsunamiTattooSupply.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("EditUser");

                    b.Navigation("Product");

                    b.Navigation("Status");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.Role", b =>
                {
                    b.HasOne("TsunamiTattooSupply.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TsunamiTattooSupply.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TsunamiTattooSupply.Models.User", "EditUser")
                        .WithMany()
                        .HasForeignKey("EditUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TsunamiTattooSupply.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("EditUser");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.RolePermission", b =>
                {
                    b.HasOne("TsunamiTattooSupply.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedUser");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.Size", b =>
                {
                    b.HasOne("TsunamiTattooSupply.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID");

                    b.HasOne("TsunamiTattooSupply.Models.User", "EditUser")
                        .WithMany()
                        .HasForeignKey("EditUserID");

                    b.HasOne("TsunamiTattooSupply.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("EditUser");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.Stock", b =>
                {
                    b.HasOne("TsunamiTattooSupply.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID");

                    b.HasOne("TsunamiTattooSupply.Models.User", "EditUser")
                        .WithMany()
                        .HasForeignKey("EditUserID");

                    b.HasOne("TsunamiTattooSupply.Models.ProductColor", "ProductColor")
                        .WithMany()
                        .HasForeignKey("ProductColorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("EditUser");

                    b.Navigation("Product");

                    b.Navigation("ProductColor");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.SubCategory", b =>
                {
                    b.HasOne("TsunamiTattooSupply.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID");

                    b.HasOne("TsunamiTattooSupply.Models.User", "EditUser")
                        .WithMany()
                        .HasForeignKey("EditUserID");

                    b.HasOne("TsunamiTattooSupply.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("EditUser");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.Unit", b =>
                {
                    b.HasOne("TsunamiTattooSupply.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID");

                    b.HasOne("TsunamiTattooSupply.Models.User", "EditUser")
                        .WithMany()
                        .HasForeignKey("EditUserID");

                    b.HasOne("TsunamiTattooSupply.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("EditUser");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TsunamiTattooSupply.Models.User", b =>
                {
                    b.HasOne("TsunamiTattooSupply.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsunamiTattooSupply.Models.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Status");

                    b.Navigation("UserType");
                });
#pragma warning restore 612, 618
        }
    }
}
